CREATE TABLE IF NOT EXISTS otps (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  wa_message_id TEXT NOT NULL,
  phone VARCHAR(15) NOT NULL,
  pin_code VARCHAR(5) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE
);
